name: AI Code Reviewer

on:
  workflow_call:
    inputs:
      # github_token, aws_access_key_id, aws_secret_access_key are removed as per user request.
      # They will be set in the environment by the calling workflow.
      aws_region:
        description: 'AWS Region for Bedrock service'
        required: true
        type: string
      heavy_model_id:
        description: 'Bedrock Model ID for detailed code analysis'
        required: true
        type: string
      light_model_id:
        description: 'Bedrock Model ID for summarizing changes'
        required: true
        type: string
      deepseek_model_id: # Name kept from plan, can be any model for refinement
        description: 'Bedrock Model ID for refining heavy model output'
        required: true
        type: string
      calling_repo_token: # Optional token
        description: 'Optional token for actions in the calling repository if GITHUB_TOKEN is insufficient'
        required: false
        type: string
    # Secrets are passed via the inputs section by the calling workflow (e.g., inputs.aws_access_key_id: ${{ secrets.CALLER_AWS_KEY }})
    # No separate secrets block is typically needed here for values passed through inputs.

jobs:
  ai_code_review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Required to post review comments
      contents: read       # Required to checkout code and read PR diff
      # Add other permissions if needed based on specific actions

    steps:
      - name: Checkout Reviewer Code
        uses: actions/checkout@v4 # Checks out this workflow's repository
        with:
          # Optional: If your Python script needs to know its own version or access its own files
          # path: ./.github/actions/reviewer-code # Example if you want to place it in a subfolder
          persist-credentials: false

      # The PR code is usually available in the context of the calling workflow's event.
      # For workflow_call, GITHUB_EVENT_PATH points to the event that triggered the calling workflow.
      # The Python script will use this event path to get PR details from the calling repo.

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Or your desired Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # working-directory: ./.github/actions/reviewer-code # If checked out to a subpath

      - name: Run AI Code Review
        run: python src/main.py
        env:
          PYTHONUNBUFFERED: "1" # For immediate log output
          AWS_DEFAULT_REGION: ${{ inputs.aws_region }} # config.py expects AWS_DEFAULT_REGION
          HEAVY_MODEL_ID: ${{ inputs.heavy_model_id }}
          LIGHT_MODEL_ID: ${{ inputs.light_model_id }}
          DEEPSEEK_MODEL_ID: ${{ inputs.deepseek_model_id }}
          CALLING_REPO_TOKEN: ${{ inputs.calling_repo_token }}
          # GITHUB_EVENT_PATH is automatically available to the script
          # GITHUB_REPOSITORY is automatically available to the script
          # BOT_NAME will be defaulted by config.py if not set here, or can be added as an input if needed.
          # GITHUB_TOKEN, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY are expected to be in the environment, set by the caller. 